name = "lucia-secure"
main = "lucia-secure/cloudflare-worker/src/worker.mjs"
compatibility_date = "2024-11-20"
workers_dev = true
node_compat = false

[vars]
# Optional defaults (you can override in dashboard)
DEEPSEEK_MODEL = "deepseek-reasoner"
ALLOW_ORIGIN = "*"
