name = "lucia-secure"
main = "src/worker.js"
compatibility_date = "2024-11-01"

# Default dev vars (overridden in dashboard)
[vars]
DUMMY_MODE = "true"
DEEPSEEK_API_URL = "https://api.deepseek.com/v1/chat/completions"
DEEPSEEK_MODEL = "deepseek-chat"
